name: ci

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions: {}

jobs:
  wait-for-previous-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for older runs to finish
        uses: fkirc/skip-duplicate-actions@v5
        with:
          # Wait for previous runs instead of cancelling them
          wait_for_previous_runs: true
          # Don't cancel other runs in the queue
          cancel_others: false
  sleep_dev_1:
    needs: wait-for-previous-runs
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Sleep for 10 seconds
        run: sleep 10

  echo_production:
    needs: sleep_dev_1
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Run echo command
        run: echo "hello"

  sleep_dev_2:
    needs: echo_production
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Sleep for 10 seconds
        run: sleep 10
